// Code generated by dbstore-gen. DO NOT EDIT.

package main

import (
	"context"

	"github.com/loykin/dbstore"
	sqlxadapter "github.com/loykin/dbstore/adapters/sqlx"
)

// UserRepoTemplate defines the per-backend query/protocol logic for
// UserRepository. Implementations receive an adapter-specific Adaptor,
// never the raw client.
type UserRepoTemplate[A any] interface {
	Create(ctx context.Context, a A, name string) error
	CreateBatch(ctx context.Context, a A, names []string) error
	FindAll(ctx context.Context, a A) ([]User, error)
	FindByID(ctx context.Context, a A, id int) (*User, error)
}

// userRepo is the only implementation of UserRepository —
// generated once for this domain interface and reused for every backend by
// parameterizing A. src is always a named field, never embedded: embedding
// would promote Runner[A].Run onto userRepo[A] itself, leaking
// infra access past the UserRepository contract.
type userRepo[A any] struct {
	tmpl UserRepoTemplate[A]
	src  dbstore.Runner[A]
}

// NewUserRepo combines a backend Template with a Runner to produce a
// UserRepository.
func NewUserRepo[A any](tmpl UserRepoTemplate[A], src dbstore.Runner[A]) UserRepository {
	return &userRepo[A]{tmpl: tmpl, src: src}
}

func (r *userRepo[A]) Create(ctx context.Context, name string) error {
	return dbstore.Exec(ctx, r.src, func(ctx context.Context, a A) error {
		return r.tmpl.Create(ctx, a, name)
	})
}

func (r *userRepo[A]) CreateBatch(ctx context.Context, names []string) error {
	return dbstore.Exec(ctx, r.src, func(ctx context.Context, a A) error {
		return r.tmpl.CreateBatch(ctx, a, names)
	})
}

func (r *userRepo[A]) FindAll(ctx context.Context) ([]User, error) {
	return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) ([]User, error) {
		return r.tmpl.FindAll(ctx, a)
	})
}

func (r *userRepo[A]) FindByID(ctx context.Context, id int) (*User, error) {
	return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) (*User, error) {
		return r.tmpl.FindByID(ctx, a, id)
	})
}

// var _ compile-time assertion: if sqlite's Template stops implementing
// UserRepoTemplate (e.g. UserRepository gained a method), this
// line fails to compile instead of the gap going unnoticed.
var _ UserRepoTemplate[sqlxadapter.Adaptor] = SqliteUserTemplate{}
