package main

import "context"

//go:generate go tool dbstore-gen -backend sqlite

// User is the domain model this example's repository works with.
type User struct {
	ID   int    `db:"id"`
	Name string `db:"name"`
}

// UserRepository is the contract application code depends on — it knows
// nothing about sqlx, SQL, or any other backend. See user_repo_sqlite.go
// for the SQLite-specific query logic and user_repo_gen.go (generated by
// `go generate`) for how the two are wired together.
type UserRepository interface {
	Create(ctx context.Context, name string) error
	CreateBatch(ctx context.Context, names []string) error
	FindByID(ctx context.Context, id int) (*User, error)
	FindAll(ctx context.Context) ([]User, error)
}
