// Code generated by dbstore-gen. DO NOT EDIT.

package main

import (
	"testing"

	"github.com/loykin/dbstore/dbstoretest"
)

func TestUserRepoCompliance(t *testing.T) {
	dbstoretest.RunComplianceSuite(t, []dbstoretest.Fixture[UserRepository, userRepoCapabilities]{
		sqliteUserFixture,
		restUserFixture,
	}, runUserRepoComplianceSuite)
}
