// Code generated by dbstore-gen. DO NOT EDIT.

package main

import (
	"context"

	"github.com/loykin/dbstore"
	restadapter "github.com/loykin/dbstore/adapters/rest"
	sqlxadapter "github.com/loykin/dbstore/adapters/sqlx"
)

// UserRepoBackend defines the per-backend query/protocol logic for
// UserRepository. Implementations receive an adapter-specific Handle,
// never the raw client.
type UserRepoBackend[A any] interface {
	Create(ctx context.Context, h A, name string) error
	CreateBatch(ctx context.Context, h A, names []string) error
	FindAll(ctx context.Context, h A) ([]User, error)
	FindByID(ctx context.Context, h A, id int) (*User, error)
}

// userRepo is the only implementation of UserRepository —
// generated once for this domain interface and reused for every backend by
// parameterizing A. src is always a named field, never embedded: embedding
// would promote Runner[A].Run onto userRepo[A] itself, leaking
// infra access past the UserRepository contract.
type userRepo[A any] struct {
	backend UserRepoBackend[A]
	src     dbstore.Runner[A]
}

// NewUserRepo combines backend-specific repository operations with a
// source-scoped Runner to produce a UserRepository.
func NewUserRepo[A any](backend UserRepoBackend[A], src dbstore.Runner[A]) UserRepository {
	return &userRepo[A]{backend: backend, src: src}
}

func (r *userRepo[A]) Create(ctx context.Context, name string) error {
	return dbstore.Exec(ctx, r.src, func(ctx context.Context, a A) error {
		return r.backend.Create(ctx, a, name)
	})
}

func (r *userRepo[A]) CreateBatch(ctx context.Context, names []string) error {
	return dbstore.Exec(ctx, r.src, func(ctx context.Context, a A) error {
		return r.backend.CreateBatch(ctx, a, names)
	})
}

func (r *userRepo[A]) FindAll(ctx context.Context) ([]User, error) {
	return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) ([]User, error) {
		return r.backend.FindAll(ctx, a)
	})
}

func (r *userRepo[A]) FindByID(ctx context.Context, id int) (*User, error) {
	return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) (*User, error) {
		return r.backend.FindByID(ctx, a, id)
	})
}

// var _ compile-time assertion: if sqlite's Backend stops implementing
// UserRepoBackend (e.g. UserRepository gained a method), this
// line fails to compile instead of the gap going unnoticed.
var _ UserRepoBackend[sqlxadapter.Handle] = SqliteUserBackend{}

// ConnectSqliteUserRepository opens "sqlite" as the sole consumer of that
// source, wires it into a SqliteUserBackend-backed UserRepository,
// and returns the resulting Close. register installs whatever this backend's
// Open needs (e.g. RegisterDefaultDrivers, or RegisterDriver with an
// app-specific implementation) — pass nil if sqlxadapter.New already
// registers what Open needs.
//
// Use this only when UserRepository is the sole consumer of "sqlite".
// If a second repository needs the same source, open it explicitly with
// sqlxadapter.New and construct both repositories over the same
// sqlxadapter.Source instead — sharing one Source keeps them on the same
// connection pool and per-source throttle instead of doubling both.
func ConnectSqliteUserRepository(register func(*sqlxadapter.Adapter), cfg dbstore.SourceConfig) (UserRepository, func(), error) {
	adapter := sqlxadapter.New()
	if register != nil {
		register(adapter)
	}
	if err := adapter.Open("sqlite", cfg); err != nil {
		adapter.Close()
		return nil, nil, err
	}
	return NewSqliteUserRepository(adapter.Source("sqlite")), adapter.Close, nil
}

// var _ compile-time assertion: if rest's Backend stops implementing
// UserRepoBackend (e.g. UserRepository gained a method), this
// line fails to compile instead of the gap going unnoticed.
var _ UserRepoBackend[restadapter.Handle] = RestUserBackend{}

// ConnectRestUserRepository opens "rest" as the sole consumer of that
// source, wires it into a RestUserBackend-backed UserRepository,
// and returns the resulting Close. register installs whatever this backend's
// Open needs (e.g. RegisterDefaultDrivers, or RegisterDriver with an
// app-specific implementation) — pass nil if restadapter.New already
// registers what Open needs.
//
// Use this only when UserRepository is the sole consumer of "rest".
// If a second repository needs the same source, open it explicitly with
// restadapter.New and construct both repositories over the same
// restadapter.Source instead — sharing one Source keeps them on the same
// connection pool and per-source throttle instead of doubling both.
func ConnectRestUserRepository(register func(*restadapter.Adapter), cfg dbstore.SourceConfig) (UserRepository, func(), error) {
	adapter := restadapter.New()
	if register != nil {
		register(adapter)
	}
	if err := adapter.Open("rest", cfg); err != nil {
		adapter.Close()
		return nil, nil, err
	}
	return NewRestUserRepository(adapter.Source("rest")), adapter.Close, nil
}
