package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBaseName(t *testing.T) {
	cases := map[string]string{
		"UserRepository": "User",
		"Repository":     "Repository", // suffix-only name keeps as-is (len guard)
		"UserStore":      "UserStore",  // no Repository suffix
	}
	for in, want := range cases {
		if got := baseName(in); got != want {
			t.Errorf("baseName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestRenderGenFile_DeduplicatesSharedAdapterImport(t *testing.T) {
	iface, err := parseInterface(fixtureFile, "UserRepository")
	if err != nil {
		t.Fatal(err)
	}
	backends := []Backend{
		{Name: "sqlite", ImportPath: "github.com/loykin/dbstore/adapters/sqlx", PkgName: "sqlxadapter"},
		{Name: "postgres", ImportPath: "github.com/loykin/dbstore/adapters/sqlx", PkgName: "sqlxadapter"},
	}
	out, err := renderGenFile(buildView(iface, backends))
	if err != nil {
		t.Fatal(err)
	}
	content := string(out)
	if got := strings.Count(content, `"github.com/loykin/dbstore/adapters/sqlx"`); got != 1 {
		t.Fatalf("sqlx import count = %d, want 1\n---\n%s", got, content)
	}
	for _, assertion := range []string{
		"var _ UserRepoBackend[sqlxadapter.Handle] = SqliteUserBackend{}",
		"var _ UserRepoBackend[sqlxadapter.Handle] = PostgresUserBackend{}",
	} {
		if !strings.Contains(content, assertion) {
			t.Fatalf("generated file missing %q\n---\n%s", assertion, content)
		}
	}
}

func TestGenerationGrowth_PreservesExistingBackendAndScaffoldsNewBackend(t *testing.T) {
	dir := t.TempDir()
	iface := &Interface{
		Name:    "UserRepository",
		Package: "fixture",
		Imports: map[string]string{},
		Methods: []Method{{Name: "Create", Params: []Param{{Name: "name", Type: "string"}}}},
	}
	sqlite := Backend{Name: "sqlite", ImportPath: "github.com/loykin/dbstore/adapters/sqlx", PkgName: "sqlxadapter"}
	sqlitePath := filepath.Join(dir, "user_repo_sqlite.go")
	initialView := buildView(iface, []Backend{sqlite})
	initialStub, err := renderBackendStub(initialView, initialView.Backends[0])
	if err != nil {
		t.Fatal(err)
	}
	initialStub = append(initialStub, []byte("\n// hand-written body marker\n")...)
	if err := os.WriteFile(sqlitePath, initialStub, 0o600); err != nil {
		t.Fatal(err)
	}

	iface.Methods = append(iface.Methods, Method{Name: "Delete", Params: []Param{{Name: "id", Type: "int"}}})
	rest := Backend{Name: "rest", ImportPath: "github.com/loykin/dbstore/adapters/rest", PkgName: "restadapter"}
	grownView := buildView(iface, []Backend{sqlite, rest})
	if err := writeIfMissing(sqlitePath, func() ([]byte, error) {
		return renderBackendStub(grownView, grownView.Backends[0])
	}); err != nil {
		t.Fatal(err)
	}
	preserved, err := os.ReadFile(sqlitePath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(preserved), "hand-written body marker") {
		t.Fatal("existing backend implementation was overwritten")
	}
	if strings.Contains(string(preserved), " Delete(") {
		t.Fatal("existing backend was unexpectedly patched; missing methods must remain an explicit compile-time task")
	}

	restPath := filepath.Join(dir, "user_repo_rest.go")
	if err := writeIfMissing(restPath, func() ([]byte, error) {
		return renderBackendStub(grownView, grownView.Backends[1])
	}); err != nil {
		t.Fatal(err)
	}
	newStub, err := os.ReadFile(restPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(newStub), " Delete(") {
		t.Fatal("new backend stub does not contain the current interface method set")
	}

	gen, err := renderGenFile(grownView)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(gen), "func (r *userRepo[A]) Delete(") {
		t.Fatal("regenerated wrapper does not contain the newly added repository method")
	}
}

func TestLowerFirstUpperFirst(t *testing.T) {
	if got := lowerFirst("User"); got != "user" {
		t.Errorf("lowerFirst(User) = %q", got)
	}
	if got := upperFirst("sqlite"); got != "Sqlite" {
		t.Errorf("upperFirst(sqlite) = %q", got)
	}
	if got := lowerFirst(""); got != "" {
		t.Errorf("lowerFirst(empty) = %q", got)
	}
}

func TestResolveBackend_RejectsInvalidNameBeforeLoadingPackage(t *testing.T) {
	_, err := resolveBackend("bad-name", "example.invalid/adapter")
	if err == nil || !strings.Contains(err.Error(), "valid Go identifier") {
		t.Fatalf("err = %v, want invalid-identifier error", err)
	}
}

func TestRenderGenFile_ProducesValidGoWithExpectedShape(t *testing.T) {
	iface, err := parseInterface(fixtureFile, "UserRepository")
	if err != nil {
		t.Fatal(err)
	}
	backends := []Backend{
		{Name: "sqlite", ImportPath: "github.com/loykin/dbstore/adapters/sqlx", PkgName: "sqlxadapter"},
	}
	view := buildView(iface, backends)

	out, err := renderGenFile(view)
	if err != nil {
		t.Fatal(err)
	}
	content := string(out)

	for _, want := range []string{
		"// Code generated by dbstore-gen. DO NOT EDIT.",
		"type UserRepoBackend[A any] interface {",
		"type userRepo[A any] struct {",
		"\tbackend UserRepoBackend[A]",
		"\tsrc     dbstore.Runner[A]",
		"func NewUserRepo[A any](backend UserRepoBackend[A], src dbstore.Runner[A]) UserRepository {",
		"func (r *userRepo[A]) FindByID(ctx context.Context, id int) (*User, error) {",
		"return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) (*User, error) {",
		"var _ UserRepoBackend[sqlxadapter.Handle] = SqliteUserBackend{}",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("generated file missing %q\n---\n%s", want, content)
		}
	}
	// src must never be an anonymous embed — the one structural guarantee
	// this generator exists to preserve.
	if strings.Contains(content, "\tdbstore.Runner[A]\n") {
		t.Error("src must be a named field, never an anonymous embed")
	}
}

func TestRenderBackendStub_SignaturesMatchBackend(t *testing.T) {
	iface, err := parseInterface(fixtureFile, "UserRepository")
	if err != nil {
		t.Fatal(err)
	}
	backends := []Backend{
		{Name: "sqlite", ImportPath: "github.com/loykin/dbstore/adapters/sqlx", PkgName: "sqlxadapter"},
	}
	view := buildView(iface, backends)

	out, err := renderBackendStub(view, view.Backends[0])
	if err != nil {
		t.Fatal(err)
	}
	content := string(out)

	for _, want := range []string{
		"type SqliteUserBackend struct{}",
		"func NewSqliteUserRepository(source sqlxadapter.Source) UserRepository {",
		"return NewUserRepo[sqlxadapter.Handle](SqliteUserBackend{}, source)",
		"func (SqliteUserBackend) Create(ctx context.Context, h sqlxadapter.Handle, name string) error {",
		"func (SqliteUserBackend) FindByID(ctx context.Context, h sqlxadapter.Handle, id int) (*User, error) {",
		`panic("TODO: implement")`,
	} {
		if !strings.Contains(content, want) {
			t.Errorf("backend stub missing %q\n---\n%s", want, content)
		}
	}
}

func TestRenderVariadicMethod_ForwardsExpandedArguments(t *testing.T) {
	iface, err := parseInterface(fixtureFile, "VariadicRepository")
	if err != nil {
		t.Fatal(err)
	}
	view := buildView(iface, []Backend{{
		Name:       "sqlite",
		ImportPath: "github.com/loykin/dbstore/adapters/sqlx",
		PkgName:    "sqlxadapter",
	}})
	generated, err := renderGenFile(view)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"M(ctx context.Context, names ...string) error",
		"return r.backend.M(ctx, a, names...)",
	} {
		if !strings.Contains(string(generated), want) {
			t.Fatalf("generated wrapper missing %q\n---\n%s", want, generated)
		}
	}
	stub, err := renderBackendStub(view, view.Backends[0])
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(stub), "M(ctx context.Context, h sqlxadapter.Handle, names ...string) error") {
		t.Fatalf("backend stub did not preserve variadic signature\n---\n%s", stub)
	}
}

func TestRenderComplianceFiles_SeparateApplicationAndGeneratedOwnership(t *testing.T) {
	iface, err := parseInterface(fixtureFile, "UserRepository")
	if err != nil {
		t.Fatal(err)
	}
	view := buildView(iface, []Backend{{
		Name:       "sqlite",
		ImportPath: "github.com/loykin/dbstore/adapters/sqlx",
		PkgName:    "sqlxadapter",
	}})

	suite, err := renderComplianceSuiteSkeleton(view)
	if err != nil {
		t.Fatal(err)
	}
	content := string(suite)
	for _, want := range []string{
		"type userRepoCapabilities struct{}",
		"caps userRepoCapabilities",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("suite skeleton missing %q\n---\n%s", want, content)
		}
	}
	if strings.Contains(content, "sqliteUserFixture") {
		t.Error("application-owned suite must not own the generated backend registry")
	}

	fixture, err := renderFixtureStub(view, view.Backends[0])
	if err != nil {
		t.Fatal(err)
	}
	fixtureContent := string(fixture)
	for _, want := range []string{
		"var sqliteUserFixture = dbstoretest.Fixture[UserRepository, userRepoCapabilities]",
		`panic("TODO: construct sqlite UserRepository")`,
	} {
		if !strings.Contains(fixtureContent, want) {
			t.Errorf("fixture skeleton missing %q\n---\n%s", want, fixtureContent)
		}
	}

	registry, err := renderComplianceRegistry(view)
	if err != nil {
		t.Fatal(err)
	}
	registryContent := string(registry)
	for _, want := range []string{
		"// Code generated by dbstore-gen. DO NOT EDIT.",
		"dbstoretest.Fixture[UserRepository, userRepoCapabilities]",
		"sqliteUserFixture",
	} {
		if !strings.Contains(registryContent, want) {
			t.Errorf("generated registry missing %q\n---\n%s", want, registryContent)
		}
	}
}
