package main

import (
	"strings"
	"testing"
)

func TestBaseName(t *testing.T) {
	cases := map[string]string{
		"UserRepository": "User",
		"Repository":     "Repository", // suffix-only name keeps as-is (len guard)
		"UserStore":      "UserStore",  // no Repository suffix
	}
	for in, want := range cases {
		if got := baseName(in); got != want {
			t.Errorf("baseName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestLowerFirstUpperFirst(t *testing.T) {
	if got := lowerFirst("User"); got != "user" {
		t.Errorf("lowerFirst(User) = %q", got)
	}
	if got := upperFirst("sqlite"); got != "Sqlite" {
		t.Errorf("upperFirst(sqlite) = %q", got)
	}
	if got := lowerFirst(""); got != "" {
		t.Errorf("lowerFirst(empty) = %q", got)
	}
}

func TestRenderGenFile_ProducesValidGoWithExpectedShape(t *testing.T) {
	iface, err := parseInterface(fixtureFile, "UserRepository")
	if err != nil {
		t.Fatal(err)
	}
	backends := []Backend{
		{Name: "sqlite", ImportPath: "github.com/loykin/dbstore/adapters/sqlx", PkgName: "sqlxadapter"},
	}
	view := buildView(iface, backends)

	out, err := renderGenFile(view)
	if err != nil {
		t.Fatal(err)
	}
	content := string(out)

	for _, want := range []string{
		"// Code generated by dbstore-gen. DO NOT EDIT.",
		"type UserRepoTemplate[A any] interface {",
		"type userRepo[A any] struct {",
		"\ttmpl UserRepoTemplate[A]",
		"\tsrc  dbstore.Runner[A]",
		"func NewUserRepo[A any](tmpl UserRepoTemplate[A], src dbstore.Runner[A]) UserRepository {",
		"func (r *userRepo[A]) FindByID(ctx context.Context, id int) (*User, error) {",
		"return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) (*User, error) {",
		"var _ UserRepoTemplate[sqlxadapter.Adaptor] = SqliteUserTemplate{}",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("generated file missing %q\n---\n%s", want, content)
		}
	}
	// src must never be an anonymous embed — the one structural guarantee
	// this generator exists to preserve (see docs/design-codegen.md).
	if strings.Contains(content, "\tdbstore.Runner[A]\n") {
		t.Error("src must be a named field, never an anonymous embed")
	}
}

func TestRenderBackendStub_SignaturesMatchTemplate(t *testing.T) {
	iface, err := parseInterface(fixtureFile, "UserRepository")
	if err != nil {
		t.Fatal(err)
	}
	backends := []Backend{
		{Name: "sqlite", ImportPath: "github.com/loykin/dbstore/adapters/sqlx", PkgName: "sqlxadapter"},
	}
	view := buildView(iface, backends)

	out, err := renderBackendStub(view, view.Backends[0])
	if err != nil {
		t.Fatal(err)
	}
	content := string(out)

	for _, want := range []string{
		"type SqliteUserTemplate struct{}",
		"func (SqliteUserTemplate) Create(ctx context.Context, a sqlxadapter.Adaptor, name string) error {",
		"func (SqliteUserTemplate) FindByID(ctx context.Context, a sqlxadapter.Adaptor, id int) (*User, error) {",
		`panic("TODO: implement")`,
	} {
		if !strings.Contains(content, want) {
			t.Errorf("backend stub missing %q\n---\n%s", want, content)
		}
	}
}
