package main

const genFileTemplate = `// Code generated by dbstore-gen. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"github.com/loykin/dbstore"
{{range .ExtraImports}}	{{.Alias}} "{{.Path}}"
{{end}}{{range .Backends}}	{{.PkgName}} "{{.ImportPath}}"
{{end}})

// {{.Base}}RepoTemplate defines the per-backend query/protocol logic for
// {{.InterfaceName}}. Implementations receive an adapter-specific Adaptor
// (never the raw client) — see docs/design-codegen.md.
type {{.Base}}RepoTemplate[A any] interface {
{{range .Methods}}	{{.Name}}({{.TemplateParams}}) {{.ReturnSig}}
{{end}}}

// {{.WrapperStruct}} is the only implementation of {{.InterfaceName}} —
// generated once for this domain interface and reused for every backend by
// parameterizing A. src is always a named field, never embedded: embedding
// would promote Runner[A].Run onto {{.WrapperStruct}}[A] itself, leaking
// infra access past the {{.InterfaceName}} contract.
type {{.WrapperStruct}}[A any] struct {
	tmpl {{.Base}}RepoTemplate[A]
	src  dbstore.Runner[A]
}

// {{.Constructor}} combines a backend Template with a Runner to produce a
// {{.InterfaceName}}.
func {{.Constructor}}[A any](tmpl {{.Base}}RepoTemplate[A], src dbstore.Runner[A]) {{.InterfaceName}} {
	return &{{.WrapperStruct}}[A]{tmpl: tmpl, src: src}
}
{{$wrapper := .WrapperStruct}}
{{range .Methods}}
func (r *{{$wrapper}}[A]) {{.Name}}({{.DomainParams}}) {{.ReturnSig}} {
{{if .HasValue}}	return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) ({{.ValueType}}, error) {
		return r.tmpl.{{.Name}}(ctx, a{{.DomainArgsPrefixed}})
	})
{{else}}	return dbstore.Exec(ctx, r.src, func(ctx context.Context, a A) error {
		return r.tmpl.{{.Name}}(ctx, a{{.DomainArgsPrefixed}})
	})
{{end}}}
{{end}}
{{range .Backends}}
// var _ compile-time assertion: if {{.Name}}'s Template stops implementing
// {{$.Base}}RepoTemplate (e.g. {{$.InterfaceName}} gained a method), this
// line fails to compile instead of the gap going unnoticed.
var _ {{$.Base}}RepoTemplate[{{.PkgName}}.Adaptor] = {{.TemplateStructName}}{}
{{end}}
`

const testSkeletonTemplate = `// Generated skeleton — dbstore-gen only creates this file if it doesn't
// exist yet (never overwrites). Add a Fixture entry for every backend you
// implement, and write the shared assertions once in the suite function
// below using only {{.InterfaceName}} methods.

package {{.Package}}

import (
	"testing"

	"github.com/loykin/dbstore/dbstoretest"
)

func Test{{.Base}}RepoCompliance(t *testing.T) {
	dbstoretest.RunComplianceSuite(t, []dbstoretest.Fixture[{{.InterfaceName}}]{
{{range .Backends}}		// TODO: {Name: "{{.Name}}", New: func(t *testing.T) {{$.InterfaceName}} { ... }, Caps: dbstoretest.Capabilities{}},
{{end}}	}, run{{.Base}}RepoComplianceSuite)
}

// run{{.Base}}RepoComplianceSuite asserts the behavior every
// {{.InterfaceName}} implementation must share. caps gates assertions not
// every backend can honor (e.g. multi-op atomicity) — see
// dbstoretest.Capabilities.
func run{{.Base}}RepoComplianceSuite(t *testing.T, newRepo func(t *testing.T) {{.InterfaceName}}, caps dbstoretest.Capabilities) {
	t.Helper()
	_ = caps
	// TODO: write assertions using only {{.InterfaceName}} methods.
}
`

const backendStubTemplate = `// Generated skeleton by dbstore-gen for backend "{{.Backend.Name}}" —
// created once, never overwritten. Fill in the TODO bodies; the signatures
// already match {{.Base}}RepoTemplate[{{.Backend.PkgName}}.Adaptor], so a
// future {{.InterfaceName}} method addition shows up here as a compile
// error (see the "var _ ..." assertion in the _gen.go file), not silently.

package {{.Package}}

import (
	"context"

	{{.Backend.PkgName}} "{{.Backend.ImportPath}}"
)

type {{.Backend.TemplateStructName}} struct{}
{{$pkg := .Backend.PkgName}}
{{range .Methods}}
func ({{$.Backend.TemplateStructName}}) {{.Name}}(ctx context.Context, a {{$pkg}}.Adaptor{{range .Params}}, {{.Name}} {{.Type}}{{end}}) {{.ReturnSig}} {
	panic("TODO: implement")
}
{{end}}
`
