package main

const genFileTemplate = `// Code generated by dbstore-gen. DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"github.com/loykin/dbstore"
{{range .Imports}}	{{.Alias}} "{{.Path}}"
{{end}})

// {{.Base}}RepoBackend defines the per-backend query/protocol logic for
// {{.InterfaceName}}. Implementations receive an adapter-specific Handle,
// never the raw client.
type {{.Base}}RepoBackend[A any] interface {
{{range .Methods}}	{{.Name}}({{.BackendParams}}) {{.ReturnSig}}
{{end}}}

// {{.WrapperStruct}} is the only implementation of {{.InterfaceName}} —
// generated once for this domain interface and reused for every backend by
// parameterizing A. src is always a named field, never embedded: embedding
// would promote Runner[A].Run onto {{.WrapperStruct}}[A] itself, leaking
// infra access past the {{.InterfaceName}} contract.
type {{.WrapperStruct}}[A any] struct {
	backend {{.Base}}RepoBackend[A]
	src     dbstore.Runner[A]
}

// {{.Constructor}} combines backend-specific repository operations with a
// source-scoped Runner to produce a {{.InterfaceName}}.
func {{.Constructor}}[A any](backend {{.Base}}RepoBackend[A], src dbstore.Runner[A]) {{.InterfaceName}} {
	return &{{.WrapperStruct}}[A]{backend: backend, src: src}
}
{{$wrapper := .WrapperStruct}}
{{range .Methods}}
func (r *{{$wrapper}}[A]) {{.Name}}({{.DomainParams}}) {{.ReturnSig}} {
{{if .HasValue}}	return dbstore.Call(ctx, r.src, func(ctx context.Context, a A) ({{.ValueType}}, error) {
		return r.backend.{{.Name}}(ctx, a{{.DomainArgsPrefixed}})
	})
{{else}}	return dbstore.Exec(ctx, r.src, func(ctx context.Context, a A) error {
		return r.backend.{{.Name}}(ctx, a{{.DomainArgsPrefixed}})
	})
{{end}}}
{{end}}
{{range .Backends}}
// var _ compile-time assertion: if {{.Name}}'s Backend stops implementing
// {{$.Base}}RepoBackend (e.g. {{$.InterfaceName}} gained a method), this
// line fails to compile instead of the gap going unnoticed.
var _ {{$.Base}}RepoBackend[{{.PkgName}}.Handle] = {{.BackendStructName}}{}

// {{.ConnectFactoryName}} opens "{{.Name}}" as the sole consumer of that
// source, wires it into a {{.BackendStructName}}-backed {{$.InterfaceName}},
// and returns the resulting Close. register installs whatever this backend's
// Open needs (e.g. RegisterDefaultDrivers, or RegisterDriver with an
// app-specific implementation) — pass nil if {{.PkgName}}.New already
// registers what Open needs.
//
// Use this only when {{$.InterfaceName}} is the sole consumer of "{{.Name}}".
// If a second repository needs the same source, open it explicitly with
// {{.PkgName}}.New and construct both repositories over the same
// {{.PkgName}}.Source instead — sharing one Source keeps them on the same
// connection pool and per-source throttle instead of doubling both.
func {{.ConnectFactoryName}}(register func(*{{.PkgName}}.Adapter), cfg dbstore.SourceConfig) ({{$.InterfaceName}}, func(), error) {
	adapter := {{.PkgName}}.New()
	if register != nil {
		register(adapter)
	}
	if err := adapter.Open("{{.Name}}", cfg); err != nil {
		adapter.Close()
		return nil, nil, err
	}
	return {{.FactoryName}}(adapter.Source("{{.Name}}")), adapter.Close, nil
}
{{end}}
`

const complianceSuiteSkeletonTemplate = `// Compliance suite skeleton created by dbstore-gen.
// This file is application-owned and is never overwritten. Write shared
// assertions below using only {{.InterfaceName}} methods.

package {{.Package}}

import (
	"testing"
)

// {{.Capabilities}} declares optional guarantees specific to
// {{.InterfaceName}}. Add fields only for behavior that some configured
// backends can guarantee and others cannot.
type {{.Capabilities}} struct{}

// run{{.Base}}RepoComplianceSuite asserts the behavior every
// {{.InterfaceName}} implementation must share. caps gates assertions not
// every backend can honor (e.g. multi-op atomicity).
func run{{.Base}}RepoComplianceSuite(t *testing.T, newRepo func(t *testing.T) {{.InterfaceName}}, caps {{.Capabilities}}) {
	t.Helper()
	_ = caps
	// TODO: write assertions using only {{.InterfaceName}} methods.
}
`

const fixtureStubTemplate = `// Fixture skeleton created by dbstore-gen for backend "{{.Backend.Name}}".
// This file is application-owned and is never overwritten. Replace the panic
// with backend setup and register cleanup with t.Cleanup.

package {{.Package}}

import (
	"testing"

	"github.com/loykin/dbstore/dbstoretest"
)

var {{.Backend.FixtureVarName}} = dbstoretest.Fixture[{{.InterfaceName}}, {{.Capabilities}}]{
	Name: "{{.Backend.Name}}",
	New: func(t *testing.T) {{.InterfaceName}} {
		t.Helper()
		panic("TODO: construct {{.Backend.Name}} {{.InterfaceName}}")
	},
}
`

const complianceRegistryTemplate = `// Code generated by dbstore-gen. DO NOT EDIT.

package {{.Package}}

import (
	"testing"

	"github.com/loykin/dbstore/dbstoretest"
)

func Test{{.Base}}RepoCompliance(t *testing.T) {
	dbstoretest.RunComplianceSuite(t, []dbstoretest.Fixture[{{.InterfaceName}}, {{.Capabilities}}]{
{{range .Backends}}		{{.FixtureVarName}},
{{end}}	}, run{{.Base}}RepoComplianceSuite)
}
`

const backendStubTemplate = `// Generated skeleton by dbstore-gen for backend "{{.Backend.Name}}" —
// created once, never overwritten. Fill in the TODO bodies; the signatures
// already match {{.Base}}RepoBackend[{{.Backend.PkgName}}.Handle], so a
// future {{.InterfaceName}} method addition shows up here as a compile
// error (see the "var _ ..." assertion in the _gen.go file), not silently.

package {{.Package}}

import (
	"context"

	{{.Backend.PkgName}} "{{.Backend.ImportPath}}"
{{range .DomainImports}}	{{.Alias}} "{{.Path}}"
{{end}}
)

type {{.Backend.BackendStructName}} struct{}

// {{.Backend.FactoryName}} is the application-facing constructor for the
// {{.Backend.Name}} implementation. Customize this function when
// {{.Backend.BackendStructName}} needs additional dependencies.
func {{.Backend.FactoryName}}(source {{.Backend.PkgName}}.Source) {{.InterfaceName}} {
	return {{.Constructor}}[{{.Backend.PkgName}}.Handle]({{.Backend.BackendStructName}}{}, source)
}
{{$pkg := .Backend.PkgName}}
{{range .Methods}}
func ({{$.Backend.BackendStructName}}) {{.Name}}(ctx context.Context, h {{$pkg}}.Handle{{range .Params}}, {{.Name}} {{if .Variadic}}...{{end}}{{.Type}}{{end}}) {{.ReturnSig}} {
	panic("TODO: implement")
}
{{end}}
`
